version: '3'
services:

  mysql:
    image: mysql:latest
    restart: always
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "dbPassword"
      MYSQL_DATABASE: "PersonsDb"
      MYSQL_USER: "dbAdmin"
      MYSQL_PASSWORD: "dbPassword"
      LANG: C.UTF-8
    ports:
      - 3306:3306
    # expose: 
    #   - 3306
    volumes:
      - mysql-data:/var/lib/mysql
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    ports:
      - 3000:8080
  web:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - db

volumes:
  mysql-data:
