version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    # depends_on:
    #   - db
    volumes:
      - ./webapp:/opt/webapp
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # MYSQL_ROOT_PASSWORD: "ashar007!"
      MYSQL_DATABASE: "PersonsDb"
      MYSQL_USER: "dbAdmin"
      MYSQL_PASSWORD: "dbPassword"
    ports:
      - 3306:3306
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    ports:
      - 3000:8080
